apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-counter-web-deployment
  namespace: data-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-counter-web
  template:
    metadata:
      labels:
        app: my-counter-web
    spec:
      containers:
      - name: my-counter-web
        image: kindservices/my-counter:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: my-counter-sidecar
        image: kindservices/datamesh-service-registry-client:latest
        imagePullPolicy: Always
        env:
          - name: HOSTPORT
            value: "http://service-registry-service.data-mesh:8080"
          - name: ID
            value: my-counter-web
          - name: FREQUENCY_IN_SECONDS
            value: "3"
          - name: BODY
            value: '{"webComponent":{"jsUrl":"http://my-counter-web.data-mesh/bundle.js","cssUrl":"http://my-counter-web.data-mesh/bundle.css","componentId":"<my-counter param_one=\"some param\"></my-counter>"},"label":"My Counter","tags":{"props":"param_one"}}'
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: my-counter-web
  namespace: data-mesh
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: my-counter-web
  ports:
  - name : default
    port: 80
    targetPort: 80